/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.WaterDelegate;
import com.water.exception.ConnectionException;
import com.water.formbean.WaterFormBean;
import com.water.pojo.WaterBusiness;
import com.water.pojo.WaterSupply;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 05-02-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="AddBusinessDetails" name="WaterFormBean"
 *                input="/AddBusinessDetails.jsp" parameter="status"
 *                scope="request" validate="true"
 * @struts.action-forward name="failure" path="/AddBusinessDetails.jsp"
 *                        redirect="true"
 * @struts.action-forward name="success" path="/AddBusinessDetails.jsp"
 *                        redirect="true"
 */
public class AddBusinessDetails extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		WaterFormBean waterFormBean = (WaterFormBean) form;
		WaterBusiness waterBusiness = new WaterBusiness(waterFormBean);
		boolean flag = false;
		try {
			flag = new WaterDelegate().addWaterbusinessDetails(waterBusiness);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._WATER_BUSINESS_SUCCESS);
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._WATER_BUSINESS_SUCCESS_FAILURE);
			return mapping.findForward(UtilConstants._SUCCESS);
		}

	}
}