/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.SecurityUserDelegate;
import com.water.formbean.ProfileFormBean;
import com.water.pojo.LoginDetails;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-21-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/HomePage.jsp"
 */
public class NewPasswordAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		boolean flag = false;
		ProfileFormBean profileFormBean = (ProfileFormBean) form;
		LoginDetails loginDetails = new LoginDetails(profileFormBean);
		try {
			flag = new SecurityUserDelegate().newPassword(loginDetails);
			if (flag) {
				request.setAttribute(UtilConstants._STATUS,
						UtilConstants._NEW_PASSWORD_SET_SUCCESS);
				return mapping.findForward(UtilConstants._SUCCESS);
			} else {
				request.setAttribute(UtilConstants._STATUS,
						UtilConstants._NEW_PASSWORD_SET_FAILURE);
				return mapping.findForward(UtilConstants._FAILURE);
			}
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._FAILURE);
		}
	}
}