/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.formbean.ProfileFormBean;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-20-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class RegisterPersonalAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ProfileFormBean profileFormBean = (ProfileFormBean) form;
		HttpSession session = request.getSession();
		session.setAttribute("profileFormBean", profileFormBean);
		return mapping.findForward(UtilConstants._SUCCESS);
	}
}