/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.WaterDelegate;
import com.water.exception.ConnectionException;
import com.water.formbean.WaterFormBean;
import com.water.pojo.WaterBusiness;
import com.water.pojo.WaterSupply;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 05-04-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/UpdateWaterCostAction" name="WaterFormBean"
 *                input="/UpdateViewWaterCostDetails.jsp" scope="request"
 *                validate="true"
 * @struts.action-forward name="failure" path="/asdfads"
 * @struts.action-forward name="success" path="/sdfadfads"
 */
public class UpdateWaterCostAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		WaterFormBean waterFormBean = (WaterFormBean) form;
		System.out.println(waterFormBean.getSupplyid());
		WaterBusiness waterBusiness = new WaterBusiness(waterFormBean);
		boolean flag = false;
		try {
			flag = new WaterDelegate().updateWaterCostDetails(waterBusiness);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._UPDATE_WATER_SUPPLY_SUCCESS);
			return mapping.findForward("success");
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._UPDATE_WATER_SUPPLY_COST);
			return mapping.findForward("success");
		}
	}
}