/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.WaterDelegate;
import com.water.exception.ConnectionException;
import com.water.formbean.WaterFormBean;
import com.water.pojo.WaterBusiness;
import com.water.pojo.WaterSupply;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 05-04-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/UpdateViewWaterCostDetails.jsp"
 */
public class UpdateViewWaterCostDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		WaterBusiness waterBusiness = null;
		boolean flag = false;
		try {
			waterBusiness = new WaterDelegate().updateViewWaterCost(Integer
					.parseInt(request.getParameter("businessid")));
			request.setAttribute("waterBusiness", waterBusiness);
			return mapping.findForward("success");
		} catch (Exception e) {
			return mapping.findForward("success");
		}
	}
}