/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.GeneralDelegate;
import com.water.exception.ConnectionException;
import com.water.pojo.Feedback;
import com.water.pojo.WaterBusiness;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 05-04-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="ViewWaterCostDetails.jsp"
 * @struts.action-forward name="success" path="ViewWaterCostDetails.jsp"
 */
public class ViewWaterCostDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		Vector<WaterBusiness> vWaterBusinesses = null;
		try {
			vWaterBusinesses = new GeneralDelegate().ViewWaterCostDetails(Integer
					.parseInt((String) session.getAttribute("cityid")), request
					.getParameter("businessfor"));
			if (!vWaterBusinesses.equals("")) {
				request.setAttribute("vWaterBusinesses", vWaterBusinesses);
				return mapping.findForward(UtilConstants._SUCCESS);
			} else {
				request.setAttribute(UtilConstants._STATUS,
						UtilConstants._VIEW_WATER_COST);
				return mapping.findForward(UtilConstants._FAILURE);
			}
		} catch (Exception e) {
			System.out.println(e);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._VIEW_WATER_COST);
			return mapping.findForward(UtilConstants._FAILURE);
		}

	}
}