/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.GeneralDelegate;
import com.water.delegate.WaterDelegate;
import com.water.exception.ConnectionException;
import com.water.pojo.TipsSuggestions;
import com.water.pojo.WaterSupply;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-26-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/ViewWaterSupplyTimeings.jsp"
 */
public class ViewCityWaterSupplyTimingsAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		Vector<WaterSupply> wSupplies = null;
		try {
			wSupplies = new WaterDelegate().viewWaterSupplyDetails(Integer
					.parseInt((String) session.getAttribute("cityid")));
			if (!wSupplies.equals("")) {
				request.setAttribute("wSupplies", wSupplies);
				return mapping.findForward(UtilConstants._SUCCESS);
			} else {
				request.setAttribute(UtilConstants._STATUS,
						UtilConstants._VIEW_WATER_FUPPLY_FAILED);
				return mapping.findForward(UtilConstants._FAILURE);
			}
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._FAILURE);
		} catch (Exception e) {
			System.out.println(e);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._VIEW_WATER_FUPPLY_FAILED);
			return mapping.findForward(UtilConstants._FAILURE);
		}
	}
}
