/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.WaterDelegate;
import com.water.exception.ConnectionException;
import com.water.pojo.WaterInfoPojo;
import com.water.util.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-29-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/ViewAdminWaterInformation.jsp"
 */
public class ViewAdminWaterInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		Vector<WaterInfoPojo> vWaterInfoPojos = null;
		try {
			vWaterInfoPojos = new WaterDelegate().viewWaterInformation(Integer
					.parseInt((String) session.getAttribute("cityid")), request
					.getParameter("water"), request.getRealPath("./images"));
			if (!vWaterInfoPojos.equals("")) {
				request.setAttribute("vWaterInfoPojos", vWaterInfoPojos);
				request.setAttribute("water", request.getParameter("water"));
				return mapping.findForward(UtilConstants._SUCCESS);
			} else {
				request.setAttribute(UtilConstants._STATUS, "NO "
						+ request.getParameter("water") + "Informatrion");
				return mapping.findForward(UtilConstants._FAILURE);
			}
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._FAILURE);
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS, "NO "
					+ request.getParameter("water") + "Informatrion");
			return mapping.findForward(UtilConstants._FAILURE);
		}

	}
}