/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.RegionalInfoDelegate;
import com.water.exception.ConnectionException;
import com.water.formbean.RegionalFormBean;
import com.water.pojo.City;
import com.water.pojo.State;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-18-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/ViewCitiesAction" name="regionalFormBean"
 *                scope="request" validate="true"
 * @struts.action-forward name="faliure" path="/ViewCities.jsp"
 * @struts.action-forward name="success" path="/ViewCities.jsp"
 */
public class ViewCitiesAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegionalFormBean regionalFormBean = (RegionalFormBean) form;// TODO
		// Auto-generated
		// method
		// stub
		String data = request.getParameter("districtid");
		String[] split = data.split(",");
		String[] names = new String[2];
		for (int i = 0; i < split.length; i++) {
			System.out.println(split[i]);
			names[i] = split[i];
		}
		Vector<City> vCities = null;
		try {
			vCities = new RegionalInfoDelegate().viewCities(regionalFormBean
					.getStateid(), Integer.parseInt(names[0]), request
					.getRealPath("./images"));
			request.setAttribute("vCities", vCities);
			request.setAttribute("stateid", regionalFormBean.getStateid());
			request
					.setAttribute("districtid", names[0]);
			request.setAttribute("statename", regionalFormBean.getStatename());
			request.setAttribute("districtname", names[1]);
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._FAILURE);
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._VIEW_STATE_FAILURE);
			return mapping.findForward(UtilConstants._FAILURE);
		}

	}
}