/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.formbean;

import java.math.BigDecimal;
import java.sql.Blob;

import org.apache.struts.action.ActionForm;

import com.water.pojo.City;

/**
 * MyEclipse Struts Creation date: 09-21-2012
 * 
 * XDoclet definition:
 * 
 * @struts.form name="GeneralFormBean"
 */
public class GeneralFormBean extends ActionForm {
	/*
	 * Generated fields
	 */

	/** suggestonsdescription property */
	private String suggestonsdescription;

	/** suggesstionid property */
	private Integer suggesstionid;

	/** cityidref property */
	private Integer cityidref;

	/** citizenname property */
	private String citizenname;

	/** emailid property */
	private String emailid;

	private int complaintid;
	private String complaintarea;
	private String complaintername;
	private String complaint;
	private String complaintsolution;
	private String complaintstatusstatus;
	private int feedbackid;
	private String feedbackitem;
	private String feedsendername;
	private String feedbackdescription;

	private String enquiryarea;
	private String enquiry;
	private String enquiryreply;
	private String enquirystatus;
	private int enquiryid;

	
	private int educationid;
	private String educationname;
	private String educationdescription;
	private String educationdocumentaion;
	private Blob educationdoc;
	private String siteurl;
	/*
	 * Generated Methods
	 */

	/**
	 * Returns the suggestonsdescription.
	 * 
	 * @return String
	 */
	public String getSuggestonsdescription() {
		return suggestonsdescription;
	}

	/**
	 * Set the suggestonsdescription.
	 * 
	 * @param suggestonsdescription
	 *            The suggestonsdescription to set
	 */
	public void setSuggestonsdescription(String suggestonsdescription) {
		this.suggestonsdescription = suggestonsdescription;
	}

	/**
	 * Returns the suggesstionid.
	 * 
	 * @return Integer
	 */
	public Integer getSuggesstionid() {
		return suggesstionid;
	}

	/**
	 * Set the suggesstionid.
	 * 
	 * @param suggesstionid
	 *            The suggesstionid to set
	 */
	public void setSuggesstionid(Integer suggesstionid) {
		this.suggesstionid = suggesstionid;
	}

	/**
	 * Returns the cityidref.
	 * 
	 * @return Integer
	 */
	public Integer getCityidref() {
		return cityidref;
	}

	/**
	 * Set the cityidref.
	 * 
	 * @param cityidref
	 *            The cityidref to set
	 */
	public void setCityidref(Integer cityidref) {
		this.cityidref = cityidref;
	}

	/**
	 * Returns the citizenname.
	 * 
	 * @return String
	 */
	public String getCitizenname() {
		return citizenname;
	}

	/**
	 * Set the citizenname.
	 * 
	 * @param citizenname
	 *            The citizenname to set
	 */
	public void setCitizenname(String citizenname) {
		this.citizenname = citizenname;
	}

	/**
	 * Returns the emailid.
	 * 
	 * @return String
	 */
	public String getEmailid() {
		return emailid;
	}

	/**
	 * Set the emailid.
	 * 
	 * @param emailid
	 *            The emailid to set
	 */
	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public int getComplaintid() {
		return complaintid;
	}

	public void setComplaintid(int complaintid) {
		this.complaintid = complaintid;
	}

	public String getComplaintarea() {
		return complaintarea;
	}

	public void setComplaintarea(String complaintarea) {
		this.complaintarea = complaintarea;
	}

	public String getComplaint() {
		return complaint;
	}

	public void setComplaint(String complaint) {
		this.complaint = complaint;
	}

	public String getComplaintsolution() {
		return complaintsolution;
	}

	public void setComplaintsolution(String complaintsolution) {
		this.complaintsolution = complaintsolution;
	}

	public String getComplaintstatusstatus() {
		return complaintstatusstatus;
	}

	public void setComplaintstatusstatus(String complaintstatusstatus) {
		this.complaintstatusstatus = complaintstatusstatus;
	}

	public String getComplaintername() {
		return complaintername;
	}

	public void setComplaintername(String complaintername) {
		this.complaintername = complaintername;
	}

	public int getFeedbackid() {
		return feedbackid;
	}

	public void setFeedbackid(int feedbackid) {
		this.feedbackid = feedbackid;
	}

	public String getFeedbackitem() {
		return feedbackitem;
	}

	public void setFeedbackitem(String feedbackitem) {
		this.feedbackitem = feedbackitem;
	}

	public String getFeedsendername() {
		return feedsendername;
	}

	public void setFeedsendername(String feedsendername) {
		this.feedsendername = feedsendername;
	}

	public String getFeedbackdescription() {
		return feedbackdescription;
	}

	public void setFeedbackdescription(String feedbackdescription) {
		this.feedbackdescription = feedbackdescription;
	}

	public String getEnquiryarea() {
		return enquiryarea;
	}

	public void setEnquiryarea(String enquiryarea) {
		this.enquiryarea = enquiryarea;
	}

	public String getEnquiry() {
		return enquiry;
	}

	public void setEnquiry(String enquiry) {
		this.enquiry = enquiry;
	}

	public String getEnquiryreply() {
		return enquiryreply;
	}

	public void setEnquiryreply(String enquiryreply) {
		this.enquiryreply = enquiryreply;
	}

	public String getEnquirystatus() {
		return enquirystatus;
	}

	public void setEnquirystatus(String enquirystatus) {
		this.enquirystatus = enquirystatus;
	}

	public int getEnquiryid() {
		return enquiryid;
	}

	public void setEnquiryid(int enquiryid) {
		this.enquiryid = enquiryid;
	}

	public int getEducationid() {
		return educationid;
	}

	public void setEducationid(int educationid) {
		this.educationid = educationid;
	}

	public String getEducationname() {
		return educationname;
	}

	public void setEducationname(String educationname) {
		this.educationname = educationname;
	}

	public String getEducationdescription() {
		return educationdescription;
	}

	public void setEducationdescription(String educationdescription) {
		this.educationdescription = educationdescription;
	}

	public String getEducationdocumentaion() {
		return educationdocumentaion;
	}

	public void setEducationdocumentaion(String educationdocumentaion) {
		this.educationdocumentaion = educationdocumentaion;
	}

	public Blob getEducationdoc() {
		return educationdoc;
	}

	public void setEducationdoc(Blob educationdoc) {
		this.educationdoc = educationdoc;
	}

	public String getSiteurl() {
		return siteurl;
	}

	public void setSiteurl(String siteurl) {
		this.siteurl = siteurl;
	}

}