/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.RegionalInfoDelegate;
import com.water.exception.ConnectionException;
import com.water.formbean.RegionalFormBean;
import com.water.pojo.District;
import com.water.pojo.State;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-17-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/addDistrictAction" name="regionalFormBean"
 *                scope="request" validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/Status.jsp"
 */
public class AddDistrictAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegionalFormBean regionalFormBean = (RegionalFormBean) form;// TODO
		// Auto-generated
		// method
		// stub
		boolean flag = false;
		District district = new District(regionalFormBean);
		try {
			flag = new RegionalInfoDelegate().addDistrict(district);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._ADD_DISTRICT);
			return mapping.findForward("success");
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward("success");
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants.__ADD_DISTRICT_FAIL);
			return mapping.findForward("success");
		}

	}
}