/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import sun.text.SupplementaryCharacterData;

import com.water.delegate.GeneralDelegate;
import com.water.delegate.WaterDelegate;
import com.water.exception.ConnectionException;
import com.water.formbean.GeneralFormBean;
import com.water.formbean.WaterFormBean;
import com.water.pojo.TipsSuggestions;
import com.water.pojo.WaterSupply;
import com.water.util.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-26-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/Status.jsp"
 */
public class AddWaterSupplyDetailsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		WaterFormBean waterFormBean = (WaterFormBean) form;
		WaterSupply waterSupply = new WaterSupply(waterFormBean);
		boolean flag = false;
		try {
			flag = new WaterDelegate().addWaterSupplyDetails(waterSupply);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._WATER_SUPPLY_SUCCESS);
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._SUCCESS);
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._TIPS_FAILURE);
			return mapping.findForward(UtilConstants._SUCCESS);
		}

	}
}