/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.RegionalInfoDelegate;
import com.water.delegate.WaterDelegate;
import com.water.exception.ConnectionException;
import com.water.pojo.City;
import com.water.pojo.WaterSupply;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-26-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/UpdateWaterSupply.jsp"
 */
public class UpdateWaterSupplyRecord extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WaterSupply waterSupply = null;
		try {
			waterSupply = new WaterDelegate().viewWaterSupplyUpdate(Integer
					.parseInt(request.getParameter("supplyid")));
			if (!waterSupply.equals("")) {
				request.setAttribute("waterSupply", waterSupply);
				request.setAttribute("supplyid", request.getParameter("supplyid"));
				return mapping.findForward(UtilConstants._SUCCESS);
			} else {
				request.setAttribute(UtilConstants._STATUS,
						UtilConstants._VIEW_CITY_FAILURE);
				return mapping.findForward(UtilConstants._FAILURE);
			}
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._FAILURE);
		} catch (Exception e) {
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._VIEW_CITY_FAILURE);
			return mapping.findForward(UtilConstants._FAILURE);
		}

	}
}