/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import java.util.Vector;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.GeneralDelegate;
import com.water.exception.ConnectionException;
import com.water.formbean.GeneralFormBean;
import com.water.pojo.Complaints;
import com.water.pojo.Enquiry;
import com.water.util.UtilConstants;

/**
 * MyEclipse Struts Creation date: 09-24-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/ViewComplaintsAction" name="GeneralFormBean"
 *                scope="request" validate="true"
 * @struts.action-forward name="failure" path="/Status.jsp"
 * @struts.action-forward name="success" path="/ViewCitizenComplaints.jsp"
 */
public class ViewComplaintsAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		Vector<Complaints> vComplaints = null;
		try {
			vComplaints = new GeneralDelegate().viewComplaints(Integer
					.parseInt((String) session.getAttribute("cityid")));
			if (!vComplaints.equals("")) {
				request.setAttribute("vComplaints", vComplaints);
				return mapping.findForward(UtilConstants._SUCCESS);
			} else {
				request.setAttribute(UtilConstants._STATUS,
						UtilConstants._VIEW_COMPLAINTS_FAILED);
				return mapping.findForward(UtilConstants._FAILURE);
			}
		} catch (ConnectionException e) {
			request.setAttribute(UtilConstants._STATUS, e.getMessage());
			return mapping.findForward(UtilConstants._FAILURE);
		} catch (Exception e) {
			System.out.println(e);
			request.setAttribute(UtilConstants._STATUS,
					UtilConstants._VIEW_COMPLAINTS_FAILED);
			return mapping.findForward(UtilConstants._FAILURE);
		}

	}
}