/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.water.strutsaction;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.water.delegate.SecurityUserDelegate;
import com.water.formbean.ProfileFormBean;
import com.water.pojo.Addresses;
import com.water.pojo.UserDetails;
import com.water.util.UtilConstants;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="failure" path="/HomePage.jsp"
 * @struts.action-forward name="success" path="/ViewUserProfile.jsp"
 */
public class ViewProfileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String path = "";
		HttpSession session = request.getSession();
		int userid = (Integer) session.getAttribute("userid");
		UserDetails userDetails = null;
		try {
			path = request.getRealPath("/images");
			userDetails = new SecurityUserDelegate().viewUserProfile(
					userid, path);
			if (userDetails != null) {
				Addresses address=userDetails.getAddresses();
				request
						.setAttribute("status",
								UtilConstants._USER_PROFILE_INFO);
				request.setAttribute("addresses", address);
				request.setAttribute("userDetails", userDetails);
				return mapping.findForward("success");

			} else {
				request.setAttribute("status", UtilConstants._NO_USER_PROFILE);
				request.setAttribute("userid", userid);
				return mapping.findForward("failure");
			}
		} catch (Exception e) {
			request.setAttribute("status", e.getMessage());
			return mapping.findForward("failure");
		}
	}
}